<?php

/**
 * Base - Any modification needs to be approved, except the space inside the block of TODO
 */

namespace App\Utils\ExtraActions;

class FilterAction extends Action
{
    protected $content;

    public function activate(string $namespace, ...$params)
    {
        $this->content = $params[0];
        return parent::activate($namespace, $params); // TODO: Change the autogenerated stub
    }

    protected function execute($id, $callback, $params)
    {
        $this->content = parent::execute(
            $id,
            $callback,
            [$this->content]
        );
        return $this->content;
    }

    protected function result()
    {
        return $this->content;
    }
}
